#!/bin/zsh
chmod -R +x ./scripts
dir=$HOME/.dotfiles
folders=("nvim", "zsh" "tmux" "scripts")
pushd $dir
for folder in $folders
do 
   echo "stowing $folder"
   stow -D $folder
   stow $folder
done
popd
