#!/usr/bin/env bash

if [ "$1" == "default" ] 
then
    pwd=$2
    host=$3
    user="postgres"
    port=5432
    db=$4
else
    pwd=$1
    host=$2
    user=$3
    port=$4
    db=$5
fi
PGPASSWORD=$pwd psql -h $host -U $user -p $port -d $db
